use hmac::{Hmac, Mac};
use sha2::{Digest, Sha256};

pub type HmacSha256 = Hmac<Sha256>;

// Key type constants for HMAC-based key generation
pub const RHO: &str = "72686f"; // "rho" in hex
pub const MU: &str = "6d75"; // "mu" in hex
pub const UM: &str = "756d"; // "um" in hex
pub const PAD: &str = "706164"; // "pad" in hex
pub const GENERATION_NONCE: [u8; 12] = [0u8; 12];

// Onion packet constants
pub const MIX_HEADER_SIZE: usize = 1300;
pub const HMAC_SIZE: usize = 32;
pub const PUBKEY_SIZE: usize = 33;
pub const VERSION_SIZE: usize = 1;
pub const ONION_PACKET_SIZE: usize = VERSION_SIZE + PUBKEY_SIZE + MIX_HEADER_SIZE + HMAC_SIZE;

/// Compute SHA256 hash of input bytes
pub fn compute_sha256(bytes: &[u8]) -> [u8; 32] {
    let mut sha256_engine = Sha256::new();
    sha256_engine.update(bytes);
    let final_hash = sha256_engine.finalize();
    final_hash.try_into().unwrap()
}

/// Generate a key for onion routing operations using HMAC-SHA256
///
/// Keys are generated by computing an HMAC (with SHA256 as hashing algorithm)
/// using the appropriate key-type (i.e. rho, mu, um, or pad) as HMAC-key
/// and the 32-byte shared secret as the message.
pub fn key_generation(key_type: &str, session_key: &[u8; 32]) -> [u8; 32] {
    let bytes = match key_type {
        "pad" => hex::decode(PAD).unwrap(),
        "rho" => hex::decode(RHO).unwrap(),
        "mu" => hex::decode(MU).unwrap(),
        "um" => hex::decode(UM).unwrap(),
        _ => panic!("Unknown key type: {}", key_type),
    };

    let mut mac = HmacSha256::new_from_slice(&bytes).unwrap();
    mac.update(session_key);
    mac.finalize().into_bytes().try_into().unwrap()
}

/// XOR two byte slices together
/// If `a` is longer than `b`, remaining bytes from `a` are preserved
pub fn xor_bytes(a: &[u8], b: &[u8]) -> Vec<u8> {
    let mut final_bytes = Vec::with_capacity(a.len());

    for (index, a_byte) in a.iter().enumerate() {
        if let Some(b_byte) = b.get(index) {
            final_bytes.push(a_byte ^ b_byte);
        } else {
            final_bytes.push(*a_byte);
        }
    }

    final_bytes
}

/// Right-shift bytes in a slice by `num` positions
/// Bytes shifted out from the end are lost, zeros are NOT filled at the start automatically
pub fn right_shift(mix_header_to_shift: &mut [u8], num: usize) {
    let len = mix_header_to_shift.len();

    for i in (0..len - num).rev() {
        mix_header_to_shift[i + num] = mix_header_to_shift[i];
    }
}

/// Convert hex string to fixed-size byte array
pub fn hex_to_bytes<const N: usize>(hex_str: &str) -> Result<[u8; N], hex::FromHexError> {
    let mut bytes = [0u8; N];
    hex::decode_to_slice(hex_str, &mut bytes)?;
    Ok(bytes)
}

/// Truncate hex string for display purposes
pub fn truncate_hex(hex_str: &str, max_len: usize) -> String {
    if hex_str.len() <= max_len {
        hex_str.to_string()
    } else {
        format!(
            "{}...{}",
            &hex_str[..max_len / 2],
            &hex_str[hex_str.len() - max_len / 2..]
        )
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_xor_bytes_equal_length() {
        let a = vec![0x01, 0x02, 0x03];
        let b = vec![0x01, 0x02, 0x03];
        let result = xor_bytes(&a, &b);
        assert_eq!(result, vec![0x00, 0x00, 0x00]);
    }

    #[test]
    fn test_xor_bytes_different_length() {
        let a = vec![0x01, 0x02, 0x03, 0x04];
        let b = vec![0x01, 0x02];
        let result = xor_bytes(&a, &b);
        assert_eq!(result, vec![0x00, 0x00, 0x03, 0x04]);
    }

    #[test]
    fn test_key_generation() {
        let secret = [0x41u8; 32]; // "AAA..."
        let rho_key = key_generation("rho", &secret);
        assert_eq!(rho_key.len(), 32);
    }
}
